services:
  wordpress:
    build: .conf/docker
    restart: unless-stopped
    ports:
      - "8090:443"    # HTTPS by default ( Caddy redirect from HTTP to HTTPS by default )
    env_file:
      - .env
    volumes:
      - ./wordpress:/var/www/html
      - ./wp-content:/var/www/html/wp-content
      - ./test.php:/var/www/html/test.php
      - ./.conf/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./.conf/caddy/Caddyfile.d:/etc/caddy/Caddyfile.d:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - db
    tty: true

  db:
    image: yobasystems/alpine-mariadb:latest
    restart: always
    ports:
      - ${LOCAL_DB_PORT:-3310}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME:-exampledb}
      MYSQL_USER: ${DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-examplepass}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-examplepass}
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
  caddy_data:
  caddy_config: